export const ERC20FactoryABI = [
    {
        "inputs":[{"internalType":"address","name":"_thbToken","type":"address"},{"internalType":"address","name":"_v2factory","type":"address"},{"internalType":"address","name":"_v2router","type":"address"}],
        "stateMutability":"nonpayable",
        "type":"constructor"
    },
    {
        "inputs":[{"internalType":"string","name":"_name","type":"string"},{"internalType":"string","name":"_symbol","type":"string"},{"internalType":"string","name":"_logo","type":"string"},{"internalType":"string","name":"_desp","type":"string"}],
        "name":"createToken",
        "outputs":[{"internalType":"address","name":"","type":"address"},{"internalType":"address","name":"","type":"address"}],
        "stateMutability":"nonpayable","type":"function"
    },
    {
        "inputs":[{"internalType":"address","name":"","type":"address"}],
        "name":"desp",
        "outputs":[{"internalType":"string","name":"","type":"string"}],
        "stateMutability":"view","type":"function"
    },
    {
        "inputs":[],
        "name":"feeCollector",
        "outputs":[{"internalType":"address","name":"","type":"address"}],
        "stateMutability":"view","type":"function"
    },
    {
        "inputs":[{"internalType":"address","name":"_pair","type":"address"}],
        "name":"graduate",
        "outputs":[{"internalType":"bool","name":"","type":"bool"}],
        "stateMutability":"nonpayable","type":"function"
    },
    {
        "inputs":[{"internalType":"uint256","name":"","type":"uint256"}],
        "name":"index",
        "outputs":[{"internalType":"address","name":"","type":"address"}],
        "stateMutability":"view","type":"function"
    },
    {
        "inputs":[{"internalType":"address","name":"","type":"address"}],
        "name":"isGraduate",
        "outputs":[{"internalType":"bool","name":"","type":"bool"}],
        "stateMutability":"view","type":"function"
    },
    {
        "inputs":[{"internalType":"address","name":"","type":"address"}],
        "name":"logo",
        "outputs":[{"internalType":"string","name":"","type":"string"}],
        "stateMutability":"view","type":"function"
    },
    {
        "inputs":[{"internalType":"address","name":"_newFeeCollector","type":"address"}],
        "name":"setFeeCollector",
        "outputs":[{"internalType":"bool","name":"","type":"bool"}],
        "stateMutability":"nonpayable","type":"function"
    },
    {
        "inputs":[],
        "name":"thbToken",
        "outputs":[{"internalType":"contract IERC20","name":"","type":"address"}],
        "stateMutability":"view","type":"function"
    },
    {
        "inputs":[],
        "name":"totalIndex",
        "outputs":[{"internalType":"uint256","name":"","type":"uint256"}],
        "stateMutability":"view","type":"function"
    },
    {
        "inputs":[],
        "name":"v2factory",
        "outputs":[{"internalType":"contract IUniswapV2Factory","name":"","type":"address"}],
        "stateMutability":"view","type":"function"
    },
    {
        "inputs":[],
        "name":"v2router",
        "outputs":[{"internalType":"contract IUniswapV2Router02","name":"","type":"address"}],
        "stateMutability":"view","type":"function"
    }
] as const;